# Python 3.10 image as a base image.
# requirements.txt is generated by pip-compile with Python 3.10.
FROM python:3.10-slim

# Setting the working directory inside the container
WORKDIR /app

# Installing the necessary dependencies
## Copy pinned requirements
COPY requirements.txt .
## Install pip-tools for pip-sync
RUN pip install pip-tools
## Running pip-sync to install the dependencies
RUN pip-sync requirements.txt
## Install Playwright and its dependencies
RUN python -m playwright install
RUN python -m playwright install-deps

# Copy the project source files to the container
COPY source/ /app/source/

# Setting environment variable for Python to run in optimised mode
ENV PYTHONUNBUFFERED=1

# Command to run the app
CMD ["python", "/app/source/main.py"]
